name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run all